# -*- coding: utf-8 -*-
"""AI analysis per \"course\" (a collection of same-named class sessions): overall summary / exam-point prediction / mock exam papers.
All based on transcripts of every recorded session for that course, generated by DeepSeek."""

from summarize import lang_note   # append a UI-language instruction so output matches the interface language

# transcripts come from speech recognition and often have homophone/near-homophone typos and misrecognized terms -- uniformly remind the model to correct them using subject knowledge
_ASR_NOTE = (
    "注意:下面的内容是课堂录音的语音识别(ASR)转写,可能有同音字/近音词/术语识别错误"
    "(例如把「映射」听成「影射」、「值域」听成「职域」)。请结合你对这门课的专业知识,"
    "自动推断老师真正想表达的正确概念和术语,据此生成结果,不要被明显的错字误导、也不要照抄错字。"
)

# math/physics formulas must display correctly in the browser -- uniformly require LaTeX, rendered on the frontend by KaTeX
_MATH_NOTE = (
    "凡是数学/物理公式、变量、上下标,一律用 LaTeX 表示:行内公式用 $...$ 包裹,独立成行的公式用 $$...$$ 包裹。"
    r"例如速度写成 $v=\frac{dx}{dt}=6t^2-6t$、合力大小写成 $F=m\omega^2\sqrt{A^2+B^2}$、单位写成 $\text{m/s}$,"
    "绝不要写成 6t^2-6t、mω^2 (A^2+B^2)^{1/2} 这种纯文本上标/花括号形式。"
    "注意输出的是 JSON,LaTeX 里的反斜杠必须转义成两个反斜杠(如 \\\\frac、\\\\omega)以保证 JSON 合法。"
)


def aggregate_summary(text, name, ds, lang="zh-Hans"):
    sys = (
        f"你是《{name}》这门课的助教。下面是这门课多次课堂录音的转写合集(按时间拼接)。"
        f"{_ASR_NOTE}"
        "**只能根据下面转写里真实讲到的内容来汇总,绝对不许凭课程名/标签名脑补,不许添加转写里根本没有的知识点、章节或学科内容。** "
        "转写讲了什么就总结什么;如果转写只是闲聊、内容很少,就如实概括实际说了什么,别硬凑成一门系统课程——这种情况 summary 直接说明内容较少即可,key_points/chapters 可以给空数组。"
        "请据实汇总成一份课程总结。输出 JSON:"
        '{"summary":"整体概述","key_points":["核心知识点..."],"chapters":[{"title":"章节/主题","points":["要点..."]}]}。'
        "key_points 给 6-12 条贯穿全课的核心知识点;chapters 按主题把内容分块。"
        f"{_MATH_NOTE}只输出 JSON。"
    )
    return ds._chat(sys + lang_note(lang), text)


def predict_exam(text, name, ds, lang="zh-Hans"):
    sys = (
        f"你是《{name}》这门课的考试分析专家。请结合两方面预测这门课最可能的考点:"
        f"(1) 你对《{name}》这类大学课程常见考点、重点概念、典型题型的了解;"
        "(2) 下面这门课的课堂录音转写里——老师【反复出现/多次讲】的概念、【明确强调的重点】、"
        "以及【明确说过会考/要考/期末考】的内容。综合给出可能的考点及其概率。"
        f"{_ASR_NOTE}考点名称请用规范的学科术语(纠正录音里的错字)。输出 JSON:"
        '{"points":[{"name":"考点名","probability":整数0-100,"reason":"为什么可能考(结合录音里老师的话或学科规律)","detail":"这个考点的具体内容、核心公式/结论、复习要点"}]}。'
        "probability 是该考点在期末出现的可能性(0-100 整数),所有 points 的 probability 之和约等于 100;"
        f"按 probability 从高到低排列,给 5-8 个考点。{_MATH_NOTE}只输出 JSON。"
    )
    return ds._chat(sys + lang_note(lang), text)


def mock_exam(text, name, ds, lang="zh-Hans"):
    sys = (
        f"你是《{name}》这门课的命题老师。请根据下面这门课的课堂录音内容,出一套贴合大学期末难度的模拟试卷。"
        f"{_ASR_NOTE}"
        "输出 JSON:"
        '{"questions":[{"type":"选择/填空/简答/计算/证明","question":"题干","answer":"参考答案(含关键步骤)","point":"对应考点"}]}。'
        "出 8-12 题,题型搭配合理、覆盖这门课的主要重点,难度贴合期末。"
        "选择题的每个选项(A、B、C、D)各占一行:在题干和每个选项之间用换行符分隔(JSON 里写成 \\n),"
        "例如 question 写成 \"……则质点速度为零的时刻为(  )\\nA. 0 和 1 s\\nB. 0 和 2 s\\nC. 1 s 和 2 s\\nD. 0 和 1.5 s\",不要把选项挤在一行。"
        f"{_MATH_NOTE}只输出 JSON。"
    )
    return ds._chat(sys + lang_note(lang), text)
